# Generated by Django 4.2.10 on 2024-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_menuitemsmodel_sale_price_menuitemsmodel_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemsmodel',
            name='popular_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
