# Generated by Django 4.2.10 on 2024-02-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0003_menuitemsmodel_popular_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='dishes.menuitemsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentUser', models.CharField(blank=True, max_length=200, null=True)),
                ('orderNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('status', models.CharField(blank=True, default='in_cart', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('items', models.ManyToManyField(blank=True, default=None, related_name='cart_items', to='cart.cartitemsmodel')),
            ],
        ),
    ]
