# Generated by Django 4.2.10 on 2024-02-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='client.customermodel'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
