# Generated by Django 4.2.10 on 2024-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_customer_cartmodel_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='payment_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
