# Generated by Django 4.2.10 on 2024-02-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_menuitemsmodel_popular_status'),
        ('cart', '0003_cartmodel_payment_method_cartmodel_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIngredientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='on', max_length=200, null=True)),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='dishes.menuitemsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cartitemsmodel',
            name='item_ingredients',
            field=models.ManyToManyField(blank=True, default=None, related_name='item_ingredients', to='cart.itemingredientsmodel'),
        ),
    ]
