# Generated by Django 4.2.10 on 2024-02-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_menuitemsmodel_popular_status'),
        ('cart', '0004_itemingredientsmodel_cartitemsmodel_item_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemingredientsmodel',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='dishes.ingredientsmodel'),
        ),
    ]
